name: Cleanup Inactive Deployments
on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Delete Inactive Deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python delete_inactive_deployments.py
